[package]
name = "onenote"
version = "0.1.0"
authors = ["Markus Siemens <markus@m-siemens.de>"]
edition = "2018"

[profile.release]
debug = true

[features]
backtrace = []

[dependencies]
bytes = "0.5"
encoding_rs = "0.8.24"
enum-primitive-derive = "0.2.1"
indexmap = "1.6.0"
num-traits = "0.2"
thiserror = "1.0"
uuid = "0.8"
widestring = "0.4.2"